server:
  port: 9000

spring:
  application:
    name: Feign-Consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://lovrth:123456@localhost:8080/eureka/,http://lovrth:123456@localhost:8081/eureka/

feign:
  hystrix:
    enabled: true

logging:
  level:
    com:
      example:
        demo:
          service:
            UserService: debug
