server:
  port: 9001

spring:
  application:
    name: server-provider2
  zipkin:
    base-url: http://localhost:9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://lovrth:123456@localhost:8080/eureka/,http://lovrth:123456@localhost:8081/eureka/

